### ISSUE TITLE
latest version (master) is not at Maven Central Repository

### ISSUE THREAD

**Issue by stefanhendriks** [nguillaumin/slick2d-maven#20]
See:

https://mvnrepository.com/artifact/org.slick2d/slick2d-core, also http://search.maven.org/#search%7Cga%7C1%7Cslick2d

this refers to version 1.0.1 which was release at 2014. 

It would be nice to have the latest version (from master) available through the mvnrepository.com. Seeing that this project is still worked on (from time to time), having a release process would make it even better.

Having this in place makes it more feasible to keep Slick2d up to date. It also is motivating for others to contribute PR's ;-). 

Suggestion:
Would be nice to have everything that passes the build and is green on the master branch being able to be 'deployed' in some sense. (perhaps even automatically?).

I am using this project with much joy, but I am concerned about the gap between LWJGL and Slick2d. It would be nice to update Slick2d and keep up with the latest developments where possible, without sacrificing my clean build process. (which is greatly thanks to the slick2d-maven package, which makes setting up my game project a walk in the park), see: https://github.com/Fundynamic/dune2themaker4j

**Comment by stefanhendriks** [comment]
I saw the original issue (https://github.com/nguillaumin/slick2d-maven/issues/7) about uploading and wanted to make clear that it is also not up to date on maven central.

**Comment by nguillaumin** [comment]
Yeah it's not up to date because it's a manual process indeed. It would be nice to automate, but I don't know how since it requires me signing the artifacts with GPG, and obviously I don't want to upload my private GPG key on a CI server... Additionally it requires some manual operations on the Sonatype OSS repo interface. Open to suggestions if you have any good ideas. Here's the current process:
* https://github.com/nguillaumin/slick2d-maven/wiki/Releasing-slick2d-maven-to-the-Sonatype-OSS-repository
* http://central.sonatype.org/pages/apache-maven.html

That being said I'll try to deploy the current version soon.

Cool game by the way, I loved Dune 2!

**Comment by nguillaumin** [comment]
1.0.2 has been published to Central: http://search.maven.org/#artifactdetails%7Corg.slick2d%7Cslick2d-parent%7C1.0.2%7Cpom

**Comment by stefanhendriks** [comment]
thanks for the updated version. Let me dive in, perhaps I can find something useful.

**Comment by stefanhendriks** [comment]
wow looks like a very tedious process. I read http://www.sonatype.org/nexus/2015/06/02/how-to-publish-software-artifacts-to-maven-central/ - looks like most of it you are doing. If all by hand, then wow...

But the gist of it, seems to be like:
- you create a gpg key (for the CI server then), and share its public key
- basically your CI server needs to be able to package the whole thing and upload it to sso.sonatype.whatever
- then you need to manually publish it to Central.

will dig further
